name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Bison Flex
      run: sudo apt-get update && sudo apt-get install flex bison -y
    - name: Set up C++ and LLVM Compiler
      run: sudo apt-get install clang -y
    - name: make
      run: make
    # cross compile for Windows
    - name: Set up C++ Compiler for Windows
      run: sudo apt install g++-mingw-w64-x86-64 -y
    - name: Make for Windows
      run: make win
    - name: Rename to formal names
      run: mv build/miniGo miniGo-linux-x64 && mv build/miniGo.exe miniGo-win-x64.exe

    # now release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}/CHANGELOG.md
        files: |
          miniGo-linux-x64
          miniGo-win-x64.exe

