name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  watch:
    types: [ started ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Bison Flex
      run: sudo apt-get update && sudo apt-get install flex bison -y
    - name: Set up C++ and LLVM Compiler
      run: sudo apt-get install clang -y
    - name: make
      run: make

    # now test by diff the output of miniGo compiler and go official compiler

    - name: Set up Go Compiler
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    - name: Diff
      run: make diff
