name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  watch:
    types: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Bison Flex
      run: sudo apt-get update && sudo apt-get install flex bison -y
    - name: Set up C++ Compiler
      run: sudo apt-get install clang -y
    - name: Set up LLVM Compiler
      run: sudo apt-get install llvm -y
    - name: make
      run: make

    # now test by diff the output of miniGo compiler and go compiler

    - name: Set up Go Compiler
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Diff
      run: make diff
